### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by kcriqui** [elliotmade/This-Button#1]
Thanks for the library. It's made dealing with buttons in my RGB laser Phaser project much cleaner. There's a typo in the readme which has a property .gpioState which is actually .gpio_state in the code. I prefer the former so I updated my local copy of the library.

Also, you might want to add the property .active to the readme. I use it because I have functions that need to start immediately and continue to run until the button is released.

**Comment by elliotmade** [comment]
Hey thanks for the comment.  I went ahead and added another property called .buttonActive (it just returns .active, but I thought that sounded less ambiguous).

**Comment by kcriqui** [comment]
Excellent. I'll grab the updated library and use the new property.
